# Generated by Django 3.2.10 on 2022-09-23 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appDijango', '0001_informacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datos',
            new_name='Post',
        ),
    ]
