# Generated by Django 3.2.10 on 2022-10-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0003_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correo',
            old_name='correo',
            new_name='correo_electronico',
        ),
    ]
