# Generated by Django 3.2.10 on 2022-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0004_rename_correo_correo_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('categoria', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
