# Generated by Django 3.2.10 on 2022-10-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0011_alter_servicios_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='user',
        ),
    ]
