# Generated by Django 3.2.10 on 2022-11-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0014_auto_20221027_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
    ]
