# Generated by Django 3.2.10 on 2023-09-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0016_noticias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Articulo a Pedir', 'verbose_name_plural': 'Lineas de Pedido'},
        ),
    ]
