# Generated by Django 3.2.10 on 2023-09-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0017_alter_lineapedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Linea Pedido', 'verbose_name_plural': 'Lineas Pedidos'},
        ),
    ]
