# Generated by Django 3.2.10 on 2023-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0018_alter_lineapedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
