# Generated by Django 3.2.10 on 2023-09-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
