# Generated by Django 3.2.10 on 2023-09-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0022_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../appDijango/static/imgs/logo.jpg', upload_to=''),
        ),
    ]
