# Generated by Django 3.2.10 on 2023-09-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appDijango', '0024_datosa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosa',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='password2',
        ),
        migrations.AlterField(
            model_name='datosa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datosA', to=settings.AUTH_USER_MODEL),
        ),
    ]
