# Generated by Django 3.2.10 on 2023-09-19 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appDijango', '0025_auto_20230919_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../appDijango/static/imgs/logo.jpg', upload_to='profile_pics/'),
        ),
    ]
