# Generated by Django 3.2.10 on 2023-09-20 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0026_auto_20230919_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosa',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='datosa',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/appDijango/static/imgs/logo.jpg', upload_to='profile_images/'),
        ),
    ]
