# Generated by Django 3.2.10 on 2023-09-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0027_auto_20230920_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosa',
            name='extra',
        ),
    ]
