# Generated by Django 3.2.10 on 2023-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0029_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosa',
            name='modificaciones',
            field=models.TextField(default=''),
        ),
    ]
