# Generated by Django 3.2.10 on 2023-09-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0032_alter_datosa_timestamp_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosa',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='timestamp_modificacion',
        ),
    ]
