# Generated by Django 3.2.10 on 2023-09-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0033_auto_20230921_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosa',
            options={'ordering': ['-timestamp_modificacion']},
        ),
        migrations.AddField(
            model_name='datosa',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
