# Generated by Django 3.2.10 on 2023-09-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0034_auto_20230921_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosa',
            options={},
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='direccion_anterior',
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='image',
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='telefono_anterior',
        ),
        migrations.RemoveField(
            model_name='datosa',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='ModificacionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_anterior', models.CharField(max_length=100)),
                ('direccion_anterior', models.CharField(max_length=100)),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True)),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='appDijango.datosa')),
            ],
        ),
    ]
