# Generated by Django 3.2.10 on 2023-09-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0035_auto_20230922_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/appDijango/static/imgs/logo.jpg', upload_to=''),
        ),
    ]
