# Generated by Django 3.2.10 on 2023-09-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0038_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='profile_images'),
        ),
    ]
