# Generated by Django 3.2.10 on 2023-09-26 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0040_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificaciondatos',
            name='imagen_anterior',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='modificaciondatos',
            name='datos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDijango.datosa'),
        ),
        migrations.AlterField(
            model_name='modificaciondatos',
            name='direccion_anterior',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modificaciondatos',
            name='telefono_anterior',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modificaciondatos',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
