# Generated by Django 3.2.10 on 2023-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0041_auto_20230926_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificaciondatos',
            name='email_anterior',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='modificaciondatos',
            name='username_anterior',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
