# Generated by Django 3.2.10 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDijango', '0042_auto_20230927_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/'),
        ),
    ]
